pipeline:
  wiki_build:
    image: nimlang/nim:latest
    commands:
      - nim compile -d:ssl --run parseWiki.nim 
  build:
    image: ruby
    commands:
      - ruby --version
      - bundle --version
      - bundle install
      - bundle exec jekyll build
  rsync:
    image: drillster/drone-rsync
    user: www-data
    hosts:
      - freeside.co.uk
    source: ./_site
    target: /var/www/freeside-site/
    secrets: [ rsync_key ]
    when:
      branch: master
      event: [push, tag, deployment]
  discord:
    image: appleboy/drone-discord
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ success, failure ]
